### PR TITLE
Html platform2 

### PR DESCRIPTION
**Pull request by PeggyWiltz**
removed the extra version of styles in the root to avoid confusion and also removed an extra jpg we don't need (original of the favicon, I have it locally if we end up needing it)

### CODE REVIEW

**Comment by spaetsch** [comment]
You deleted the wrong version of styles.css. The one in root had all of our changes from Friday. I'm going to see if I can revert it.

**Comment by PeggyWiltz** [comment]
Oh crap, sorry.  I made an assumption since you had done the moving around that the one in the folder was right, I should have checked.

Date: Sun, 14 Jun 2015 16:21:58 -0700

**Comment by spaetsch** [comment]
No worries. The right version of the right file is now in the right place. (bonus git practice! :) Just wanted to let you know, so you can be sure to get it when you sync your fork to master (and aren't perplexed when you see the notification about the change).

**Comment by PeggyWiltz** [comment]
Okay, thanks again

Date: Mon, 15 Jun 2015 02:55:09 -0700

**Pull request merged**
